sudo: required

language: node_js

install:
  - yarn install --frozen-lockfile
  # - wget https://github.com/gohugoio/hugo/releases/download/v0.45.1/hugo_extended_0.45.1_Linux_64bit.deb
  - wget https://github.com/gohugoio/hugo/releases/download/v0.45.1/hugo_0.45.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - hugo version

script: hugo

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: renzo.lucioni.xyz
  skip_cleanup: true
  local_dir: public
  cache_control: "max-age=21600"

after_deploy: yarn run invalidate
