dist: xenial

language: node_js

addons:
  snaps:
    - name: hugo
      channel: extended/stable
    - name: aws-cli
      channel: latest/stable
      classic: true

cache:
  directories:
    - $HOME/.npm

install: true

script: ./scripts/build.sh

deploy:
  on:
    branch: master
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
