# https://docs.travis-ci.com/user/reference/overview/#linux
# https://wiki.ubuntu.com/Releases
dist: xenial

language: node_js

git:
  depth: 3

cache: npm

install: ./scripts/install.sh
script: make build

deploy:
  on:
    branch: master
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
