dist: xenial

language: python
python: 3.7

addons:
  snaps:
    - name: hugo
      channel: extended/stable

cache:
  pip: true
  directories:
    - $HOME/.npm

env:
  global:
    - NVM_VERSION=0.34.0
    - NPM_VERSION=6.4.1

install: true

script: ./scripts/build.sh

deploy:
  on:
    branch: master
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
