sudo: required

language: python
python:
  - "3.6"

cache:
  pip: true
  directories:
    - node_modules

env:
  global:
    - HUGO_VERSION=0.48
    - NVM_VERSION=0.33.11

install: true

script: ./scripts/build.sh

deploy:
  on:
    branch: master
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
