language: python
python:
  - "3.6"

cache:
  pip: true
  directories:
    - node_modules

env:
  global:
    - HUGO_VERSION=0.48
    - NVM_VERSION=0.33.11

install: ./scripts/install.sh

script: make build

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: renzo.lucioni.xyz
  skip_cleanup: true
  local_dir: public
  cache_control: "max-age=21600"

after_deploy:
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
