dist: xenial

language: node_js

git:
  depth: 3

addons:
  snaps:
    - name: hugo
      channel: extended/stable
    - name: aws-cli
      channel: latest/stable
      classic: true

cache: npm

script: make build

deploy:
  on:
    branch: master
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
