baseURL = "https://renzo.lucioni.xyz/"
languageCode = "en-us"
title = "Renzo Lucioni"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject = true
enableRobotsTXT = true
googleAnalytics = "UA-33031883-4"

# https://xyproto.github.io/splash/docs/all.html
pygmentsStyle = "monokai"
pygmentsCodeFences = true
pygmentsOptions = "linenos=true"

[params]
description = "Renzo Lucioni's personal website. Writing about past projects, fun problems, and data visualization."

[permalinks]
posts = "/:filename/"

[imaging]
quality = 100
# https://github.com/disintegration/imaging
resampleFilter = "Lanczos"

[markup]
defaultMarkdownHandler = "blackFriday"
