baseURL = "https://renzo.lucioni.xyz/"
languageCode = "en-us"
title = "Renzo Lucioni"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject = true
enableRobotsTXT = true
googleAnalytics = "UA-33031883-4"

# https://xyproto.github.io/splash/docs/all.html
pygmentsStyle = "algol_nu"
pygmentsCodeFences = true
pygmentsOptions = "linenos=true"

[permalinks]
posts = "/:filename/"

[imaging]
quality = 100
# https://github.com/disintegration/imaging
resampleFilter = "Lanczos"
